### PR TITLE
Log the actual URL requested

### PR DESCRIPTION
**Pull request by obulat**
Currently, the DelayedRequester logs base_url and the query params:

```bash
[2021-05-25 11:16:10,553] {wikimedia_commons.py:76} INFO - Processing Wikimedia Commons API for date: 2021-05-25
[2021-05-25 11:16:10,561] {requester.py:36} INFO - Processing request for url: https://commons.wikimedia.org/w/api.php
[2021-05-25 11:16:10,561] {requester.py:37} INFO - Using query parameters {'action': 'query', 'generator': 'allimages', 'gaisort': 'timestamp', 'gaidir': 'newer', 'gailimit': 250, 'prop': 'imageinfo|globalusage', 'iiprop': 'url|user|dimensions|extmetadata|mediatype', 'gulimit': 250, 'gunamespace': 0, 'format': 'json', 'gaistart': '1621900800', 'gaiend': '1621987200'}
[2021-05-25 11:16:10,561] {requester.py:38} INFO - Using headers {'User-Agent': 'CC-Catalog/0.1 (https://creativecommons.org; data-engineering@creativecommons.org)'}
```

 Adding the actual requested URL to the log makes debugging easier because you can see the URL of the page that was requested, and manually test it.
 
 ```
[2021-05-25 11:41:33,330] {requester.py:44} INFO - Received response from url https://commons.wikimedia.org/w/api.php?action=query&generator=allimages&gaisort=timestamp&gaidir=newer&gailimit=250&prop=imageinfo%7Cglobalusage&iiprop=url%7Cuser%7Cdimensions%7Cextmetadata%7Cmediatype&gulimit=250&gunamespace=0&format=json&gaistart=1621814400&gaiend=1621900800
```

### CODE REVIEW

**Review by krysal — DISMISSED** [review]
It works! And thanks for the detailed explanation again ☺️

**Review by zackkrida — DISMISSED** [review]
Naturally, this will increase the size of logs, but I think the benefits to debugging are worth the increase.

**Comment by obulat** [comment]
> Naturally, this will increase the size of logs, but I think the benefits to debugging are worth the increase.
@zackkrida Thank you for your comment, it made me think more about it.

I could also move these lines:
```
[2021-05-25 11:16:10,561] {requester.py:36} INFO - Processing request for url: https://commons.wikimedia.org/w/api.php
[2021-05-25 11:16:10,561] {requester.py:37} INFO - Using query parameters {'action': 'query', 'generator': 'allimages', 'gaisort': 'timestamp', 'gaidir': 'newer', 'gailimit': 250, 'prop': 'imageinfo|globalusage', 'iiprop': 'url|user|dimensions|extmetadata|mediatype', 'gulimit': 250, 'gunamespace': 0, 'format': 'json', 'gaistart': '1621900800', 'gaiend': '1621987200'}
[2021-05-25 11:16:10,561] {requester.py:38} INFO - Using headers {'User-Agent': 'CC-Catalog/0.1 (https://creativecommons.org; data-engineering@creativecommons.org)'}
```
to the except clause, so they would only be logged if there is an error in request.

In this way, we would greatly reduce the log size: these are the lines that we will get in the log:

#### Successful requests with a response with OK status
```
[2021-05-25 11:16:10,553] {wikimedia_commons.py:76} INFO - Processing Wikimedia Commons API for date: 2021-05-25
[2021-05-25 11:41:33,330] {requester.py:44} INFO - Received response from url https://commons.wikimedia.org/w/api.php?action=query&amp;generator=allimages&amp;gaisort=timestamp&amp;gaidir=newer&amp;gailimit=250&amp;prop=imageinfo%7Cglobalusage&amp;iiprop=url%7Cuser%7Cdimensions%7Cextmetadata%7Cmediatype&amp;gulimit=250&amp;gunamespace=0&amp;format=json&amp;gaistart=1621814400&amp;gaiend=1621900800
```
Two lines instead of three. But one URL can be longer than the previous two lines :) Actually, if the response is successful, we might not need the full URL in production, so we could have a short URL in prod, but full URL for development, maybe?

#### Successful requests with a response without OK status (Headers could be important for debugging):
```
[2021-05-25 11:16:10,553] {wikimedia_commons.py:76} INFO - Processing Wikimedia Commons API for date: 2021-05-25
[2021-05-25 11:41:33,330] {requester.py:44} INFO - Unable to request URL: https://commons.wikimedia.org/w/api.php?action=query&amp;generator=allimages&amp;gaisort=timestamp&amp;gaidir=newer&amp;gailimit=250&amp;prop=imageinfo%7Cglobalusage&amp;iiprop=url%7Cuser%7Cdimensions%7Cextmetadata%7Cmediatype&amp;gulimit=250&amp;gunamespace=0&amp;format=json&amp;gaistart=1621814400&amp;gaiend=1621900800
[2021-05-25 11:16:10,561] {requester.py:38} INFO - Using headers {'User-Agent': 'CC-Catalog/0.1 (https://creativecommons.org; data-engineering@creativecommons.org)'}
Status code: 503
```

#### Requests resulting in an error:
```
[2021-05-25 11:16:10,553] {wikimedia_commons.py:76} INFO - Processing Wikimedia Commons API for date: 2021-05-25
[2021-05-25 11:16:10,561] {requester.py:36} INFO - Processing request for url: https://commons.wikimedia.org/w/api.php
[2021-05-25 11:16:10,561] {requester.py:37} INFO - Using query parameters {'action': 'query', 'generator': 'allimages', 'gaisort': 'timestamp', 'gaidir': 'newer', 'gailimit': 250, 'prop': 'imageinfo|globalusage', 'iiprop': 'url|user|dimensions|extmetadata|mediatype', 'gulimit': 250, 'gunamespace': 0, 'format': 'json', 'gaistart': '1621900800', 'gaiend': '1621987200'}
[2021-05-25 11:16:10,561] {requester.py:38} INFO - Using headers {'User-Agent': 'CC-Catalog/0.1 (https://creativecommons.org; data-engineering@creativecommons.org)'}
[2021-05-25 11:16:10,561] {requester.py:36} INFO - Actual url: https://commons.wikimedia.org/w/api.php?action=query&amp;generator=allimages&amp;gaisort=timestamp&amp;gaidir=newer&amp;gailimit=250&amp;prop=imageinfo%7Cglobalusage&amp;iiprop=url%7Cuser%7Cdimensions%7Cextmetadata%7Cmediatype&amp;gulimit=250&amp;gunamespace=0&amp;format=json&amp;gaistart=1621814400&amp;gaiend=1621900800
```

**Comment by zackkrida** [comment]
LGTM after updates, no need for re-review.

**Review by dhruvkb — DISMISSED** [review]

**Pull request merged**
