### PR TITLE
Don't delete custom pools during test cleanup

### PR DESCRIPTION
**Pull request by stacimc**
## Description

The tests for `SingleRunExternalDAGsSensor` remove all pools and reinstate the default pool during test cleanup. The consequence is that when you run `just test` locally, any custom pools that you have defined in your local Airflow are wiped. This is specifically annoying because we have a custom `data_refresh` pool used for the data refresh DAGs, so it must be re-added every time you run tests locally.

This PR just updates the tests to make sure we only clean up the specific test pool created in the file.

## Testing Instructions

* Add a new pool through the Admin > Pools menu (or http://localhost:9090/pool/add). Make sure to save.
* Run `just test`
* Refresh the pools list in Airflow and verify your pools are still there 🎉 

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by AetherUnbound — APPROVED** [review]
Great little QoL change 😄 This would have been covered by #461 too, but at least they won't be constantly deleted and re-added now!

**Comment by stacimc** [comment]
> Great little QoL change 😄 This would have been covered by https://github.com/WordPress/openverse-catalog/issues/461 too, but at least they won't be constantly deleted and re-added now!

Definitely, and #461 will also still be necessary when running `recreate`/etc. But this has been such a nuisance with testing, I should've fixed it earlier!

**Comment by AetherUnbound** [comment]
> #461 will also still be necessary when running `recreate`/etc.

Oh that's right! Great point!

**Review by sarayourfriend — APPROVED** [review]
:tada:

**Pull request merged**
