### PR TITLE
Add missing `MD5` hash to foreign id comparison

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Fixes WordPress/openverse#1568 by @AetherUnbound

## Description

This PR adds a missing `md5` hash to the query that compares foreign ids for equality. This should make the query faster.

## Testing Instructions

I don't know how to test this change.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by stacimc — CHANGES_REQUESTED** [review]
Does the comparison on [L290](https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/common/loader/sql.py#L290) also need to be updated?

I wonder if running Finnish Museums could be used to test this, since its long-running load step was likely a symptom of the problem.

**Comment by obulat** [comment]
> Does the comparison on [L290](https://github.com/WordPress/openverse-catalog/blob/main/openverse_catalog/dags/common/loader/sql.py#L290) also need to be updated?

I guess `<>` is still `equals` under the hood, right? 😆 Great catch!

> I wonder if running Finnish Museums could be used to test this, since its long-running load step was likely a symptom of the problem.

Do you mean testing _in prod_? Or trying it out locally or in dev, with Finnish Museums DAG?

**Comment by stacimc** [comment]
> Do you mean testing in prod? Or trying it out locally or in dev, with Finnish Museums DAG?

I think we'd have to look in prod to see whether it significantly speeds up the Finnish Museum loading step. As far as testing this PR, I think we can just run a couple of DAGs and make sure that the loading step completes successfully. I tested a couple of providers and this looks good 👍

**Review by stacimc — APPROVED** [review]

**Review by krysal — APPROVED** [review]
It'll require quite a bit of data to prove this but it looks good.

**Comment by sarayourfriend** [comment]
Unassigning myself given there are already two reviewers.

**Pull request merged**
