### PR TITLE
Fix italics for duration disclosure

### PR DESCRIPTION
**Pull request by stacimc**
## Description

I added some disclosure text to the `load_completion` Slack message for reingestion workflows which is meant to be in italics, but left off the closing `_` character:

Screen Shot 2022-10-04 at 10 32 56 AM

This PR just fixes the italics :) 

## Testing Instructions

This should be straightforward, but if you want to test this manually you need to run the `wikimedia_reingestion_workflow`.

Reingestion workflows take a long time to run, so I'd recommend first updating Wikimedia's configuration in `provider_reingestion_workflows.py` to reduce the number of reingestion days. Example:

```
ProviderReingestionWorkflow(
        dag_id="wikimedia_reingestion_workflow",
        <...>

        # Add this
        daily_list_length=2,

        # Comment these out
        # daily_list_length=6,
        # one_month_list_length=9,
        # three_month_list_length=18,
        # six_month_list_length=30,
    ),
```

Then set an `ingestion_limit` Airflow variable to a small number of records (eg `100`), and run the `wikimedia_reingestion_workflow`.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by AetherUnbound — APPROVED** [review]
Such an easy thing to miss!

**Review by zackkrida — APPROVED** [review]
_great job!

**Comment by zackkrida** [comment]
And it's complete overkill but I wonder if some seperation could make the italics clearer, something like:

```py
  message += (
    "\n"
    "_"
    "Duration is the sum of the duration for each data pull 
    " It does not include loading time and does not account for data"
    " pulls that may happen concurrently."
    "_"
)
```

**Review by krysal — APPROVED** [review]

**Comment by zackkrida** [comment]
@stacimc anything blocking merge here?

**Comment by AetherUnbound** [comment]
I can't think of anything, I'll go ahead and merge it 😄

**Pull request merged**
