### PR TITLE
Add tags option for provider workflows & "legacy-ingestion" tag

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Description

This PR adds a `legacy-ingestion` tag to any provider ingestion DAG which has not yet been refactored. This was instigated by some testing I was performing locally - I wasn't sure which DAGs I could run which would actually respect `ingestion_limit` (or any other feature we're building using the new `ProviderDataIngester` class!). This makes it very easy to determine which DAGs are legacy and which use the new class.

image

## Testing Instructions

1. `just recreate`
1. Visit http://localhost:9090/ and observe the new tags
1. Visit http://localhost:9090/home?tags=legacy-ingestion to see _only_ the legacy provider DAGs
1. (Optional) Add a `tags=` override to any of the [provider workflows](https://github.com/WordPress/openverse-catalog/blob/8e2b676c0dd5d8e06b3272a74784a1b3db4c5acb/openverse_catalog/dags/providers/provider_workflows.py#L110-L114) and observe that the new tag appears in the UI after a few moments.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by rwidom — APPROVED** [review]
Awesome! I did check the recommended tests and tried adding in my own tag on one legacy and one new provider and it worked like a charm. This makes me want to go and check back in github and see if/how I can help get the remaining providers over the finish line on refactoring.

**Review by krysal — APPROVED** [review]
Looks good!

I saw a comment about adding emojis to differentiate the tags given [the color of the tag can't be chosen yet](https://github.com/apache/airflow/issues/16432), seems like a good idea.

**Comment by AetherUnbound** [comment]
> Awesome! I did check the recommended tests and tried adding in my own tag on one legacy and one new provider and it worked like a charm. This makes me want to go and check back in github and see if/how I can help get the remaining providers over the finish line on refactoring.

Great news @rwidom, we have a milestone for it! 😄 https://github.com/WordPress/openverse-catalog/milestone/8

Please feel free to assign yourself one or several!

**Comment by AetherUnbound** [comment]
> I saw a comment about adding emojis to differentiate the tags given [the color of the tag can't be chosen yet](https://github.com/apache/airflow/issues/16432), seems like a good idea.

Aww, that's a bummer, but I like the emojis! Just like our issue labels!

**Pull request merged**
