### PR TITLE
Use safe_search param to restrict results from Flickr

### LINKED ISSUE #407: Consider usage of `safe_search` param in Flickr provider script
## Problem

Flickr's API does not appear to have a way to view the safe_search setting of individual image results, but it _does_ allow searches to have a set `safe_search` level. Potentially we could use this in our provider script _or_ create an async cleanup job that identifies the status of these images.

Flickr API Docs: https://www.flickr.com/services/api/flickr.photos.search.html

**Edit:** Flickr [recently announced some new restrictions](https://blog.flickr.net/en/2022/03/17/flickr-forever-2022/) for mature and explicit content in Flickr.

Moderate and Restricted content (definitions [here](https://www.flickrhelp.com/hc/en-us/articles/4404064374164-Set-the-Safety-Levels-of-Your-Flickr-Content-or-Account), basically any partial or full nudity) is going to be restricted to Flickr pro accounts.

## Additional context

- Many images on Flickr aren't reliably marked as `Moderate` or `Restricted` , even if they contain nudity. These are unfortunately the kinds of things that make their way into Openverse most frequently.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by stacimc**
## Fixes

Fixes #407 by @zackkrida 

## Description

Adds the [`safe_search` query_param](https://www.flickr.com/services/api/flickr.photos.search.html), set to 'safe', to our search query in the Flickr provider script. This _should_ filter out results that are Moderate or Restricted as defined by Flickr's [content safety levels](https://www.flickrhelp.com/hc/en-us/articles/4404064374164-Set-the-Safety-Levels-of-Your-Flickr-Content-or-Account).

## Testing Instructions

You should at least run the Flickr provider DAG and verify that you start seeing results written to disk. I'm less certain how to test the actual filtering.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by AetherUnbound — APPROVED** [review]
LGTM!

**Review by zackkrida — APPROVED** [review]
Looks good! It's hard to gauge what impact this will have on the results from Flickr, but it can't hurt.

**Comment by krysal** [comment]
Will this filtering in the script be temporary?

**Comment by stacimc** [comment]
> Will this filtering in the script be temporary?

Maybe @zackkrida can confirm, but my understanding is that the intention is to permanently filter moderate/strict content

**Comment by zackkrida** [comment]
@krysal At some point in the future Flickr will also be removing mature content for non-pro users, so they may make the behavior used by this PR the default/only behavior, anyway.

**Pull request merged**
