### PR TITLE
Allow string as exceptions in `on_failure_callback`

### LINKED ISSUE #693: Exception in on failure callback may not be of type Exception
## Description

We are expecting the exception which gets handed to the `on_failure_callback` Slack function to be a subclass of `Exception`. 

https://github.com/WordPress/openverse-catalog/blob/9fea6554e32cd6116464a527ace57ab59b3d0a16/openverse_catalog/dags/common/slack.py#L309

It seems there are some cases (notably when a task is set to failed in the UI) that the exception is actually a string (with some extra logging from me):

```
[2022-08-24, 03:38:22 UTC] {slack.py:308} ERROR - exception='task marked as failed externally' type(exception)=<class 'str'>
[2022-08-24, 03:38:22 UTC] {taskinstance.py:1752} ERROR - Error when executing on_failure_callback
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1750, in _run_finished_callback
    task.on_failure_callback(context)
  File "/usr/local/airflow/openverse_catalog/dags/common/slack.py", line 310, in on_failure_callback
    if "Upstream task(s) failed" in exception.args:
AttributeError: 'str' object has no attribute 'args'
```

## Additional context

We can add the following change to catch this case:

```diff
diff --git a/openverse_catalog/dags/common/slack.py b/openverse_catalog/dags/common/slack.py
index e953e14c..ac72cb00 100644
--- a/openverse_catalog/dags/common/slack.py
+++ b/openverse_catalog/dags/common/slack.py
@@ -306,7 +306,10 @@ def on_failure_callback(context: dict) -> None:
 
     if exception:
         # Forgo the alert on upstream failures
-        if "Upstream task(s) failed" in exception.args:
+        if (
+            isinstance(exception, Exception)
+            and "Upstream task(s) failed" in exception.args
+        ):
             log.info("Forgoing Slack alert due to upstream failures")
             return
         exception_message = f"""
```

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes #693 by @AetherUnbound

## Description

This PR allows strings to be passed in as the exception to an `on_failure_callback`.

See #693 for a longer description of the problem.

## Testing Instructions

`just test`

Optionally attempt to fail a provider pull media task locally. You should see the failure callback still logged (instead of an exception). Here's an example, with extra logging added at the beginning to emphasise what was handed in:

```
[2022-08-24, 03:43:25 UTC] {slack.py:308} ERROR - exception='task marked as failed externally' type(exception)=<class 'str'>
[2022-08-24, 03:43:25 UTC] {slack.py:227} INFO - 
*DAG*: `cleveland_museum_workflow`
*Task*: `pull_image_data`
*Execution Date*: 2022-07-01T00:00:00Z
*Log*: http://localhost:8080/log?execution_date=2022-07-01T00%3A00%3A00%2B00%3A00&task_id=pull_image_data&dag_id=cleveland_museum_workflow&map_index=-1

*Exception*: task marked as failed externally
*Exception Type*: `builtins.str`

[2022-08-24, 03:43:25 UTC] {base.py:68} INFO - Using connection ID 'slack_alerts' for task execution.
```

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by stacimc — APPROVED** [review]
LGTM, this cleans things up considerably 😄

Completely out of curiosity, are you able to reproduce the `Upstream task(s) failed` exception handling? I've tried raising an error in `copy_to_s3` for example, which causes `load_from_s3` to enter the `upstream_failed` state, but there's no log file at all for the task. From the docs (and I was even curious enough to check the [source](https://airflow.apache.org/docs/apache-airflow/2.0.1/_modules/airflow/models/dag.html#DAG.handle_callback)) it clearly fires the callback in this state so this check definitely _should_ be necessary to prevent Slack messages from all downstream failures.

**Comment by AetherUnbound** [comment]
> Completely out of curiosity, are you able to reproduce the `Upstream task(s) failed` exception handling? I've tried raising an error in `copy_to_s3` for example, which causes `load_from_s3` to enter the `upstream_failed` state, but there's no log file at all for the task. From the docs (and I was even curious enough to check the [source](https://airflow.apache.org/docs/apache-airflow/2.0.1/_modules/airflow/models/dag.html#DAG.handle_callback)) it clearly fires the callback in this state so this check definitely _should_ be necessary to prevent Slack messages from all downstream failures.

Admittedly, this was some code I had where I was interacting with an older version of Airflow 😅 It's possible this interaction has changed or may just not be necessary at all 🤔 It's also possible this callback is being run on the scheduler rather than a whole worker being spun up just to handle the callback. I'll try and see where this is happening.

**Comment by AetherUnbound** [comment]
Okay I've poked around a bit - I thought perhaps that the logs for callbacks on the upstream task failed tasks could be found in the scheduler logs or something, but I can't find them _anywhere_. The Airflow source code is a bit hard to pull apart in these cases, so it's hard to know if it's even being called, honestly! I'll leave it as-is for now though, it doesn't hurt to have.

**Comment by stacimc** [comment]
@AetherUnbound thanks for humoring me! Definitely not a concern for the PR, but an interesting mystery 😄

**Review by zackkrida — APPROVED** [review]
> see the failure callback still logged 

I indeed did! LGTM.

**Review by obulat — APPROVED** [review]
LGTM!

**Pull request merged**
