### PR TITLE
Fix dagrun conf for provider scripts

### PR DESCRIPTION
**Pull request by stacimc**
## Description

In #707 we noticed that iNaturalist was overriding `__init__` but not passing through `*args` to `super`. This prevents configuration options set up in the dagrun conf from being initialized correctly on the ingester class.

After reviewing the other provider scripts that had already been refactored before the addition of that conf arg, I noticed that we needed to update several others!

## Testing Instructions

For each of Museum Victoria, Science Museum, and Stocksnap:
* try manually running the DAG with a dagrun conf setting `initial_query_params`
* verify in the logs of the `pull_data` task that the DAG used your supplied params

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by AetherUnbound — COMMENTED** [review]
Nice! It looks like the args are also handed explicitly for the Met ingester, could that one be changed in this PR as well? 

https://github.com/WordPress/openverse-catalog/blob/8ac257cde51f39ef4ec1b9c6b68d836c630105c1/openverse_catalog/dags/providers/provider_api_scripts/metropolitan_museum.py#L49

**Comment by stacimc** [comment]
@AetherUnbound Updated for Met as well, good call :) I've also passed through `**kwargs` as there are some tests that pass `date` for example as a kwarg for convenience, and it seems reasonable to be as generic as possible.

**Review by AetherUnbound — APPROVED** [review]
Looks great!

**Review by krysal — APPROVED** [review]
LGTM! Aren't new tests needed for the configurations? How can we prevent this from happening again?

**Comment by stacimc** [comment]
@krysal Good point, and interesting question -- I'll create an issue for this, but I think we'll need to have something along the lines of our dag parsing tests, where we iterate over the `provider_workflows` and try to initialize all of the ingester classes.

**Pull request merged**
