### PR TITLE
airflow dockerfile: set `PYTHONPATH` to DAGs folder

### LINKED ISSUE #512: DAGs folder is not present in `PYTHONPATH`
## Description

Reported by @rwidom

When running `just ipython`, the DAGs folder is set as the current working directory, so imports from the `common` module and others work fine:

https://github.com/WordPress/openverse-catalog/blob/1fda166d6f8ac4cba14dce6c3c83207adc497cc2/justfile#L81

However, since the DAG folder isn't explicitly in the `PYTHONPATH`, `just shell` gives different results. The imports _will_ work after importing something from Airflow though, because Airflow modifies the `PYTHONPATH` to include the dags folder.

```bash
$ just shell
docker-compose --file=docker-compose.yml --file=docker-compose.override.yml up -d 
[+] Running 3/3
 ⠿ Container openverse-catalog-postgres-1   Running                                                                                                                                                            0.0s
 ⠿ Container openverse-catalog-s3-1         Running                                                                                                                                                            0.0s
 ⠿ Container openverse-catalog-webserver-1  Running                                                                                                                                                            0.0s
docker-compose --file=docker-compose.yml --file=docker-compose.override.yml exec webserver /bin/bash
airflow@649a98304b20:~$ python -c "from common import storage"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'common'
airflow@649a98304b20:~$ python -c "from airflow import settings; from common import storage"
airflow@649a98304b20:~$ PYTHONPATH=/usr/local/airflow/openverse_catalog/dags/ python -c "from common import storage"
```

We should add an explicit declaration of `PYTHONPATH` in the Dockerfile so that the DAGs folder is always available to python no matter how entering the container is performed.Probably somewhere around here: 

https://github.com/WordPress/openverse-catalog/blob/1fda166d6f8ac4cba14dce6c3c83207adc497cc2/docker/airflow/Dockerfile#L17-L18

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by tal66**
## Fixes

Fixes #512 by @AetherUnbound

## Description

Adds the DAGs folder to the PYTHONPATH within the Docker container.

## Testing Instructions

Per #512, run:
1. `just shell`
1. `python -c "from common import storage"`
1. Observe that no `ModuleNotFoundError` exception is raised.

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by AetherUnbound** [comment]
Thanks for the contribution @tal66! I've edited your PR description so it aligns with our template. I'm having some trouble testing this locally, but I have a feeling it's something on my end.

**Comment by AetherUnbound** [comment]
I'm going to rebase this to include the changes from #502 and make sure it still passes CI

**Review by AetherUnbound — APPROVED** [review]
Looks good to me, works great with the test commands!

**Review by dhruvkb — APPROVED** [review]

**Comment by zackkrida** [comment]
Hi @tal66 if you ever want to chat about Openverse and contributing more, we have a community Slack channel (#openverse) in the Making WordPress Slack Instance. You can learn how to join here, if you're interested:

https://make.wordpress.org/chat/

**Pull request merged**
