### PR TITLE
Add trailing slash to Jamendo thumbnail URLs

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes https://github.com/WordPress/openverse/issues/871 (from an upstream data perspective)

## Description

This PR adds a trailing slash to Jamendo thumbnail URLs if it does not already have one. This is to ensure compatibility with our thumbnail provider, Photon, which is not able to follow redirects when generating thumbnails. See the above issue for more details.

## Testing Instructions

`just test` should be sufficient, since this alters the output of one of the tests.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by stacimc — COMMENTED** [review]
It looks like this is only updating the `set_thumbnail` but not the `thumbnail`, which does not use `_remove_trackid`.

On a related note, does this mean we need to manually update the set thumbnails in the API DB as well?

**Review by dhruvkb — APPROVED** [review]
LGTM, good fix!

**Comment by AetherUnbound** [comment]
Oh shoot, you're totally right! Good find there Staci, it looks like it:

```sql
deploy@localhost:openledger> select thumbnail from audioset where provider='jamendo' limit 10;
+----------------------------------------------------------------+
| thumbnail                                                      |
|----------------------------------------------------------------|
| https://usercontent.jamendo.com?type=album&id=100007&width=300 |
| https://usercontent.jamendo.com?type=album&id=100008&width=300 |
| https://usercontent.jamendo.com?type=album&id=100009&width=300 |
| https://usercontent.jamendo.com?type=album&id=10001&width=300  |
| https://usercontent.jamendo.com?type=album&id=100010&width=300 |
| https://usercontent.jamendo.com?type=album&id=100013&width=300 |
| https://usercontent.jamendo.com?type=album&id=100018&width=300 |
| https://usercontent.jamendo.com?type=album&id=100020&width=300 |
| https://usercontent.jamendo.com?type=album&id=100023&width=300 |
| https://usercontent.jamendo.com?type=album&id=100026&width=300 |
+----------------------------------------------------------------+
SELECT 10
Time: 0.100s
```

I'll make a note of that in the issue and execute a similar update.

**Review by stacimc — APPROVED** [review]
LGTM! I happened to have some Jamendo data locally with the 'bad' urls, so was even able to confirm that re-running the DAG updates them :)

**Pull request merged**
