### PR TITLE
Upgrade Airflow to 2.3, python to 3.10

### LINKED ISSUE #498: Upgrade to Airflow 2.3
## Description

[Airflow 2.3 has been released!](https://airflow.apache.org/blog/airflow-2.3.0/) With it come some pretty rad improvements around dynamic tasks, the replacement of the tree view with the new "grid view", and an ever-important addition of the [`SmoothOperator`  :saxophone::sunglasses:](https://airflow.apache.org/blog/airflow-2.3.0/#other-small-features)

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes #498 by @AetherUnbound

## Description

This PR upgrades Airflow to 2.3.0, and python to 3.10. I've also addressed some deprecation warnings that came up during testing.

One particularly exciting feature is the new "grid" view, which will replace the "tree" view. It's a lot more understandable!
Screenshot_2022-05-17_14-13-18

## Testing Instructions

1. `just recreate`
1. `just test`
1. Run some DAGs!

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — CHANGES_REQUESTED** [review]
I'm not sure if this is related, but I get a test failure for Jamendo: 
```
 test_get_image_pages_returns_correctly_with_no_results ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
[gw3] linux -- Python 3.10.4 /usr/local/bin/python

    def test_get_image_pages_returns_correctly_with_no_results():
        expect_result = None
        with patch.object(jamendo.delayed_requester, "get_response_json", return_value={}):
>           actual_result = jamendo._get_batch_json()

tests/dags/providers/provider_api_scripts/test_jamendo.py:39:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
openverse_catalog/dags/providers/provider_api_scripts/jamendo.py:118: in _get_batch_json
    return force_duplicates(results)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

results = None

    def force_duplicates(results):
>       if len(results) > 2:
E       TypeError: object of type 'NoneType' has no len()

openverse_catalog/dags/providers/provider_api_scripts/jamendo.py:123: TypeError
```

**Comment by AetherUnbound** [comment]
Hmmm, I'm not able to replicate that myself 😮 @WordPress/openverse-maintainers are any of y'all able to replicate Olga's failure?

**Review by stacimc — APPROVED** [review]
Exciting! 🎉 I like the Grid view, excited to play around with it a bit more. Already it looks like it's going to be a bit smoother to manually update DR/TI statuses, which is nice.

I ran the data refreshes and a few provider scripts, and it looks good! I ran the tests several times and I can't reproduce the Jamendo error - I also ran the Jamendo script and it looks to be working fine.

**Review by obulat — APPROVED** [review]

**Review by krysal — APPROVED** [review]
I ran Jamendo and Freesound scripts partially and so far everything looks good!

I wonder if it's worth using the [Airflow Docker imag](https://hub.docker.com/r/apache/airflow)e, _might_ make it even easier to upgrade in the future. Is there a reason why we don't use it?

**Comment by zackkrida** [comment]
....@krysal, that's an amazing question! 😮

**Comment by AetherUnbound** [comment]
Great question! It's worth noting that the Airflow Dockerfile is...[very complicated](https://github.com/apache/airflow/blob/main/Dockerfile). This also lets us add the different entrypoints & modifications as @zackkrida mentioned. As it stands, the current upgrade path seems pretty easy, but it would be worth checking out what it would take to use the upstream Docker image! I'm not sure yet how they manage installing Postgres or any of the provider scripts. When I used the official docker image during my trial, you specified a list of python packages that you wanted to install and it would install those _every time the container started_ 😬 not great for local development!

**Comment by zackkrida** [comment]
These seem like good reads related to this:

https://airflow.apache.org/docs/apache-airflow/stable/production-deployment.html#
https://airflow.apache.org/docs/docker-stack/index.html

Also interesting, from https://airflow.apache.org/docs/apache-airflow/stable/howto/set-up-database.html#setting-up-a-postgresql-database: 

> Airflow is known - especially in high-performance setup - to open many connections to metadata database. This might cause problems for Postgres resource usage, because in Postgres, each connection creates a new process and it makes Postgres resource-hungry when a lot of connections are opened. Therefore we recommend to use [PGBouncer](https://www.pgbouncer.org/) as database proxy for all Postgres production installations. PGBouncer can handle connection pooling from multiple components, but also in case you have remote database with potentially unstable connectivity, it will make your DB connectivity much more resilient to temporary network problems. Example implementation of PGBouncer deployment can be found in the [Helm Chart for Apache Airflow](https://airflow.apache.org/docs/helm-chart/stable/index.html) where you can enable pre-configured PGBouncer instance with flipping a boolean flag. You can take a look at the approach we have taken there and use it as an inspiration, when you prepare your own Deployment, even if you do not use the Official Helm Chart.

**Comment by zackkrida** [comment]
Some interesting ideas here too: https://aws.amazon.com/blogs/containers/running-airflow-on-aws-fargate/

Getting into infrastructure territory, however :)

**Comment by AetherUnbound** [comment]
Nice, we're using most of those "production deployment" patterns already! I'll make a ticket for looking into using the upstream airflow image - we could always use it as a base and throw our own requirements & whatnot in there.

As for PGBouncer, I've gotten close to setting it up at every previous job I've had but never gotten around to it 😅 It's definitely something we should consider as Airflow gets larger, but not a limit we're currently pushing I think.

That Fargate doc looks interesting! For a team our size though, if we want to scale out it might be better to use a managed airflow instance like Astronomer or AWS's MWAA.

**Pull request merged**
