### PR TITLE
Only drop load table if it exists

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

This addresses an issue identified by @rwidom as part of #549: Previously, our `pull_data` tasks would either succeed or fail, it was not possible for them to be skipped (even if they didn't pull any data). Now that we're introducing pre-ingestion tasks, it's possible that upstream tasks might skip the rest of the workflow. In these cases, the `create_table` step was skipped successfully, but the `delete_table`'s trigger rules were setup such that it was unconditionally run. This would then cause issues where it would try to delete a table that did not exist (see [here](https://github.com/WordPress/openverse-catalog/pull/549#discussion_r930949202)).

## Description

This PR adds an `IF EXISTS` clause to the drop table SQL to ensure that, even if the create table step doesn't run, the unconditionally run drop table step should succeed.

As part of this, I also wanted to see if I could add a test to catch this (and make sure the suggested fix actually addressed the issue). This proved to be more difficult than I thought, since Airflow tests usually involve task-specific unit tests or general DAG parsing rather than a full DAG run. I was able to get this working with the [`DebugExecutor`](https://airflow.apache.org/docs/apache-airflow/stable/executor/debug.html), but it turns out that each run takes at lest 20 seconds (and a total of 3 tests means that's at least an extra minute on tests).

These tests don't need to be run locally every time we're doing rapid iteration, so I opted to set up a new pytest CLI parameter which could selectively skip these longer-running tests. By default, `pytest` will now skip those long tests, but `pytest --extended` will run all of the available tests. Here's the time comparison:

```bash
$ pytest
...

Results (7.63s):
    1307 passed
       3 skipped

$ pytest --extended
...

Results (84.10s):
    1310 passed
```

As such, I've also added the `--extended` flag to our CI/CD so it always gets run on GitHub Actions for PRs.

## Testing Instructions

1. `just recreate`
1. Run `git checkout 3316d6d9243b90487e4ccbdd3ffaee141154f37d` (this will checkout the commit which proves the current setup fails)
1. Run `just test` and observe failure
1. Run `git checkout bugfix/drop-table-if-exists` (this will switch back to the tip of this branch)
1. Run `just test` and notice the rapid test completion
1. Run `just test --extended` and notice the longer test completion with no tests skipped

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by AetherUnbound** [comment]
Thanks Rebecca! And good questions. This step is only to clear out the loading table, and is also specifically set up to clean up the table even if things go wrong. If we get to the drop step, I can't imagine a scenario where we'd care that it wasn't present when trying to delete it, since some error in creating the table would either be identified upstream or cause an error with copying the data into the main media type table. So I think we're clear here in all cases!

**Review by obulat — APPROVED** [review]
Interesting that a tiny change in code lead to so much improvement in tests :)

**Comment by rwidom** [comment]
> Thanks Rebecca! And good questions. This step is only to clear out the loading table, and is also specifically set up to clean up the table even if things go wrong. If we get to the drop step, I can't imagine a scenario where we'd care that it wasn't present when trying to delete it, since some error in creating the table would either be identified upstream or cause an error with copying the data into the main media type table. So I think we're clear here in all cases!

Right, and I just realized that it will still report on whatever happened upstream in the reporting step. Yay! I'm so glad this worked out!

**Review by rwidom — APPROVED** [review]

**Review by krysal — APPROVED** [review]
> Interesting that a tiny change in code lead to so much improvement in tests :)

+1 to what Olga said! A cool compromise between speed and test coverage, learning a lot here of to test DAGs :)

**Review by stacimc — APPROVED** [review]
Just piling on to say it looks great to me as well! I always learn something looking at your testing code, @AetherUnbound 😄

**Comment by AetherUnbound** [comment]
Thanks all! 😄 I keep needing to get myself out of the headspace of "this is a one line change" when the reality is that testing it is a much more complicated matter 😅 Glad folks are okay with this approach!

**Pull request merged**
