### PR TITLE
Update Europeana endpoint

### LINKED ISSUE #109: Update Europeana endpoint and accomodate v2 API changes
## Current Situation

1. The current integration of the Europeana API uses the `https://www.europeana.eu/api/v2/search.json` endpoint. However Europeana has changed it's API endpoint to `https://api.europeana.eu/` to better manage traffic. This change has been noted in their API docs [here](https://pro.europeana.eu/page/search#get-started). Corresponding change should be made in the present API integration script. 
2. Some fields have been changed in v2 API. The backward compatibility of v1 API may be stopped anytime. Hence the API script needs to be modified according to the new fields. ( [list](https://pro.europeana.eu/page/search#v1) of modified fields)
3. Above changes also need to be made in the test files wherever required.

## Suggested Improvement

In the Europeana provider script, change value of `ENDPOINT` to `https://api.europeana.eu/`. Update the provider script and test suite with new fields according to v2 API. Ensure that the scripts run properly after making the changes.

## Benefit

Currently the old endpoint is still working. However this might change. Accommodating above changes will ensure that Europeana integration is updated.

### PR DESCRIPTION
**Pull request by stacimc**
## Fixes

Fixes #109 by @dravadhis 

## Description

This PR updates the Europeana DAG to use the new API endpoint under https://api.europeana.eu/ as noted in the [docs](https://pro.europeana.eu/page/search#get-started).

Happily I believe no additional changes were necessary. The API documentation is quite good and I was able to confirm all the fields we're using are present and unchanged, including the cursor based pagination. 

## Testing Instructions

Tests should all continue to pass.

Try running the Europeana DAG locally and verify the script still works. For more thorough testing I did the following:

1. Set an `INGESTION_LIMIT` of 200
2. Run the DAG until it completes ingestion for a day with a good amount of data. `2022-11-04` had 200+ rows.
3. Find the tsv for your test day in the MinIO console and download it
4. Checkout `main` and repeat steps 1-3 with the old API endpoint. Make sure you run ingestion _for the same day_. You can trigger a manual DagRun with a conf set to `{"date": "2022-11-04"}`
5. Once you have both tsvs downloaded, compare them to make sure they are identical:
```
$ cmp --silent file1 file2 && echo 'Success' || echo 'Failure: Files are different'
```

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [ ] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible
      errors.
- [ ] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
Great! The DAG works locally.

**Review by AetherUnbound — APPROVED** [review]
Wow, I'm pleased it was such a small change 😄 I tested using your instructions and everything matched 💯

**Review by krysal — CHANGES_REQUESTED** [review]
Glad that it is just a small change! The docstring also needs an update of the endpoint for preventing any confusion in the future.

**Comment by stacimc** [comment]
> The docstring also needs an update of the endpoint for preventing any confusion in the future.

Good catch, thank you @krysal! I updated the docstring to link to the documentation for the new endpoint.

**Review by krysal — APPROVED** [review]
Thank you!

**Pull request merged**
