### PR TITLE
Round duration for provider ingestion completion message

### LINKED ISSUE #373: Format "Airflow DAG Load Data Complete" duration
## Description

The notifications are _amazing_! But currently show the [`duration`](https://github.com/WordPress/openverse-catalog/blob/5188b388759a00c42785ca79f0c96949396d4d68/openverse_catalog/dags/common/loader/reporting.py#L18) in seconds like this:

CleanShot 2022-02-23 at 18 06 05@2x

We might want to:

- Round
- Convert to a human readable duration  (for example, "47 minutes", "1 hour", or alternatively something like "hh:mm:ss")

This is a _very_ minor concern 😄 

### Relevant file

https://github.com/WordPress/openverse-catalog/blob/5188b388759a00c42785ca79f0c96949396d4d68/openverse_catalog/dags/common/loader/reporting.py#L18

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes #373 by @zackkrida

## Description

This PR rounds the `duration` value for successful provider runs to 2 decimal places. These runs are usually on the order of minutes/hours/days, so we don't need more than centisecond resolution.

I also added some tests, which might be _a bit_ overkill, but it couldn't hurt :woman_shrugging:

### Before

```
*Provider*: `staten_museum`
*Media Type*: `image`
*Number of Records Upserted*: 46102
*Duration of data pull task*: 162.36981462899894

* _Duration includes time taken to pull data of all media types._
```

### After

```
*Provider*: `staten_museum`
*Media Type*: `image`
*Number of Records Upserted*: 46102
*Duration of data pull task*: 162.37

* _Duration includes time taken to pull data of all media types._
```

## Testing Instructions

`just test`

Optionally, run the Staten Museum DAG to completion (should only take a couple of minutes) and observe that the message produced in `report_load_completion` is appropriately rounded.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by stacimc — APPROVED** [review]
LGTM 🚀 

Screen Shot 2022-03-18 at 11 42 32 AM

**Review by zackkrida — APPROVED** [review]
Lgtm! Minor nit, could we add a unit like 's' or 'seconds' for folks?

**Comment by AetherUnbound** [comment]
> Minor nit, could we add a unit like 's' or 'seconds' for folks?

That's a great point! Adding that now!

**Comment by AetherUnbound** [comment]
Okay, I've actually taken a bit of a different tack here and instead humanized the entire duration value. The results now look like this:
image

The flip side is that we lose all sub-second resolution which, again, I don't really foresee being an issue (and if we want to do fine-grain analysis, we'll have the full floats stored in the XComs table anyway). What do you think @zackkrida @stacimc ?

**Comment by stacimc** [comment]
New values look great, I think that's all the resolution we need 🚀

**Pull request merged**
