### PR TITLE
Add Openverse email to DAG default args

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Description

This PR adds the `CONTACT_EMAIL` (presently openverse@wordpress.org) to the `email` section of the DAG default args. This is a precursor to getting alert emails working, since Airflow first needs an address to send said emails to.

## Testing Instructions

You should be able to go to the "Details" page of any DAG locally and see that `email` is now defined under the "Default Args" section.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]

**Review by sarayourfriend — APPROVED** [review]

**Comment by sarayourfriend** [comment]
@AetherUnbound are Airflow variables available there? If so, what's the trade off to use an environment variable instead of the airflow variable? Do environment variables require a redeployment with the catalogue as well?

**Comment by AetherUnbound** [comment]
Yes, environment variables would require a deployment to change whereas Airflow Variables can be changed on the fly. We had a longer discussion about this which you can see here: #209 

The environment variable I used here already existed and was in use elsewhere, so I just opted to use it here 🙂 we could just as easily hard-code it or use an Airflow Variable. I think the advantage to using an env var is that you don't have to have the Airflow metastore available when running a script directly. This is used in the [`provider_details.py` file](https://github.com/WordPress/openverse-catalog/blob/a2e1d50ff3c7b4c131a77313e11db63201b5c701/openverse_catalog/dags/common/loader/provider_details.py#L112), which _could_ be run outside of the Docker/Airflow setup.

**Comment by sarayourfriend** [comment]
Gotcha.

> This is used in the [provider_details.py file](https://github.com/WordPress/openverse-catalog/blob/a2e1d50ff3c7b4c131a77313e11db63201b5c701/openverse_catalog/dags/common/loader/provider_details.py#L112), which could be run outside of the Docker/Airflow setup

What is the use case for running this or any other script outside of the deployed Airflow?

**Comment by AetherUnbound** [comment]
Many of the provider scripts were (seemingly) originally set up to be able to run on their own, inside a Python virtual environment without interacting with the Airflow infrastructure. I presume this was so that they could be run outside the context of a DAG. More and more we're tying these provider scripts into Airflow infrastructure, so I don't believe it will be as relevant or necessary going forward.

However, Airflow Variables are useful for values we foresee changing frequently, or values where we wouldn't want to have to issue a deployment in order to change. Since this value already existed in the environment (so no deployment is necessary) and we're unlikely to change the value in the near future, I think it's fine as-is.

**Pull request merged**
