### PR TITLE
Remove alternate image extraction from SMK, fix foreign landing URL

### LINKED ISSUE #875: Duplicates identified in SMK data
## Description

As part of creating an announcement for the recent reingestion of SMK data, we noticed that there were duplicates that existed within our data. For instance, this search yields a few duplicate images: https://wordpress.org/openverse/search/image/?q=nature&source=smk

@obulat identified that this was because the same images had two different foreign identifiers (and URLs):

> On that page we can see that two of the Nature morte pictures are the same, but they have different URLs and probably foreign IDs (which is how we determine if the images are the same or not): https://iip.smk.dk/iiif/jp2/KMSKMSsp210.tif.reconstructed.tif.jp2/full/!2048,/0/default.jpg
> @aetherunbound, do you know if we had any SMK items previously? The only difference between the two items seems to be the prefix before (what I think is) the foreign ID: `9306t251c_`. 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes #875 by @AetherUnbound

## Description

This PR accomplishes two changes for SMK:
1. Removes the extraction of alternative images - see #875 for the rationale
1. Fixes an issue where the constructed foreign landing URL had a space in it

For the latter case, many of these URLs _must_ have a space in them it turns out! But I'm not sure how everything downstream would handle a URL that's technically a valid URL if you paste it into a browser (since most convert spaces these days) but doesn't use the correct encoding. The new change will explicitly encode them so they're in a valid state throughout our datastream.

**Example data before**:
```
+------------------------------------------------------+------------------------------------------------------------------------------+
| foreign_landing_url                                  | url                                                                          |
|------------------------------------------------------+------------------------------------------------------------------------------|
| https://open.smk.dk/en/artwork/image/KKS7055 verso   | https://api.smk.dk/api/v1/thumbnail/0386f6f1-f6b6-4b02-af0d-62242df35d0d.jpg |
| https://open.smk.dk/en/artwork/image/KKS9203 verso   | https://api.smk.dk/api/v1/thumbnail/040c1cb6-1923-4238-a71c-08ff13ac616a.jpg |
| https://open.smk.dk/en/artwork/image/KKS6537 verso   | https://api.smk.dk/api/v1/thumbnail/00aa9d7a-a17e-4721-9ce8-56c921879d1c.jpg |
| https://open.smk.dk/en/artwork/image/KKS7819 verso   | https://api.smk.dk/api/v1/thumbnail/011dcedd-106d-4206-ad23-6b0a3895c9dc.jpg |
| https://open.smk.dk/en/artwork/image/KKS7081/2 verso | https://api.smk.dk/api/v1/thumbnail/00975050-5950-4b6b-802f-44f9d0e020d8.jpg |
| https://open.smk.dk/en/artwork/image/KKS7829 verso   | https://api.smk.dk/api/v1/thumbnail/00383e3a-54b1-499c-a5de-7671ddc87860.jpg |
| https://open.smk.dk/en/artwork/image/KMSB 36 101.7   | https://api.smk.dk/api/v1/thumbnail/00699228-b5aa-45b6-9329-f3861a9b731b.jpg |
| https://open.smk.dk/en/artwork/image/KKSgb4576 verso | https://api.smk.dk/api/v1/thumbnail/007cdf70-872a-4f47-b554-2b3fdaf598bf.jpg |
| https://open.smk.dk/en/artwork/image/KMSB 15         | https://api.smk.dk/api/v1/thumbnail/012931bc-01d4-48a3-b258-8d5710580583.jpg |
| https://open.smk.dk/en/artwork/image/KKS7445k verso  | https://api.smk.dk/api/v1/thumbnail/013ac45e-3d6e-48ba-b979-d32c8cdcc3f8.jpg |
+------------------------------------------------------+------------------------------------------------------------------------------+
```

**Example data after**:
```
+---------------------------------------------------------+------------------------------------------------------------------------------+
| foreign_landing_url                                     | url                                                                          |
|---------------------------------------------------------+------------------------------------------------------------------------------|
| https://open.smk.dk/en/artwork/image/KKS7829%20verso    | https://api.smk.dk/api/v1/thumbnail/00383e3a-54b1-499c-a5de-7671ddc87860.jpg |
| https://open.smk.dk/en/artwork/image/KMSB%2036%20101.7  | https://api.smk.dk/api/v1/thumbnail/00699228-b5aa-45b6-9329-f3861a9b731b.jpg |
| https://open.smk.dk/en/artwork/image/KKSgb4576%20verso  | https://api.smk.dk/api/v1/thumbnail/007cdf70-872a-4f47-b554-2b3fdaf598bf.jpg |
| https://open.smk.dk/en/artwork/image/KKS7081/2%20verso  | https://api.smk.dk/api/v1/thumbnail/00975050-5950-4b6b-802f-44f9d0e020d8.jpg |
| https://open.smk.dk/en/artwork/image/KKS6537%20verso    | https://api.smk.dk/api/v1/thumbnail/00aa9d7a-a17e-4721-9ce8-56c921879d1c.jpg |
| https://open.smk.dk/en/artwork/image/KKS7819%20verso    | https://api.smk.dk/api/v1/thumbnail/011dcedd-106d-4206-ad23-6b0a3895c9dc.jpg |
| https://open.smk.dk/en/artwork/image/KMSB%2015          | https://api.smk.dk/api/v1/thumbnail/012931bc-01d4-48a3-b258-8d5710580583.jpg |
| https://open.smk.dk/en/artwork/image/KKS7445k%20verso   | https://api.smk.dk/api/v1/thumbnail/013ac45e-3d6e-48ba-b979-d32c8cdcc3f8.jpg |
| https://open.smk.dk/en/artwork/image/KMSB%20150         | https://api.smk.dk/api/v1/thumbnail/01507fa2-9be8-473c-b455-44d83a171eef.jpg |
| https://open.smk.dk/en/artwork/image/KMSB%2038%20102.11 | https://api.smk.dk/api/v1/thumbnail/01aa3f8f-2630-47aa-9b48-56332f00d215.jpg |
+---------------------------------------------------------+------------------------------------------------------------------------------+

```

Once this is merged and deployed, we'll want to delete the existing SMK records and re-enable the DAG.

## Testing Instructions

1. Check out `main`
1. Disable any ingestion limits you have set up for dev (SMK is really quick, thankfully)
1. Run the DAG, verify that there are about 58k results loaded, and run the following SQL (using `just db-shell`) to see the malformed foreign landing URLS: `select foreign_landing_url, url from image where provider='smk' and foreign_landing_url ilike '% %' limit 10`.
1. Check out this branch
1. Run the DAG, and verify that there are now about 39k results loaded. The following SQL should now show the same records as before, except with the appropriate (now clickable!) foreign landing URLs: `select foreign_landing_url, url from image where provider='smk' and foreign_landing_url ilike '%\%20%' limit 10`

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.
- [x] I ran the DAG documentation generator (if applicable).

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by stacimc — APPROVED** [review]
LGTM! Tests as expected. Thanks for leaving in the regression test and comment about the removal as well 💯

Should we open an issue for deleting the SMK data and re-running the DAG after this is merged?

**Comment by AetherUnbound** [comment]
I think I'd like to do those steps as a fast-follow to merging this PR, so I'd rather wait to merge it and do it all at once if that's okay!

**Review by krysal — COMMENTED** [review]
Good catch on that of the URL with random spaces! Was it purely lucky to find those spaces in a few rows while querying? Or how did you find it? I believe it would be nice to add that extra check to the MediaStore class (or something more refined for URLs in general).

All changes look good to me here. However, I was thinking if there is a way to preserve the links of the canonical images. Do you think we could use the `watermarked` column temporarily for that? It's set to `False` by default for all rows so we can make it `True` here and after a run of this DAG we can clean the "non-watermarked" images as those should be the alternative images we don't want anymore. It will require coming back and modifying this DAG to remove that flagging but it's a tiny change, and I believe it's worth it to preserve the links.

**Comment by AetherUnbound** [comment]
> Good catch on that of the URL with random spaces! Was it purely lucky to find those spaces in a few rows while querying? Or how did you find it? I believe it would be nice to add that extra check to the MediaStore class (or something more refined for URLs in general).

It was luck alone, but that's a good idea! Normally I would consider spaces in a URL to be a sign of something wrong with the data but it appears to be perfectly valid here so perhaps `MediaStore` validation would be the best plan 🙂 I'll add that!

> All changes look good to me here. However, I was thinking if there is a way to preserve the links of the canonical images. Do you think we could use the `watermarked` column temporarily for that? It's set to `False` by default for all rows so we can make it `True` here and after a run of this DAG we can clean the "non-watermarked" images as those should be the alternative images we don't want anymore. It will require coming back and modifying this DAG to remove that flagging but it's a tiny change, and I believe it's worth it to preserve the links.

Do you mind elaborating on this a bit more? What do you mean by canonical images in this case?

**Comment by krysal** [comment]
> What do you mean by canonical images in this case?

I mean just the images we want to preserve, the ones that SMK itself shows on the landing page (not the pretty similar ones). What I mean at the end with coming back to the DAG is to remove the watermark flagging after the duplicated images are deleted. It would be only a temporary trick.

**Comment by AetherUnbound** [comment]
Ahhh, okay I see what you mean! Instead of running a deletion, we alter the DAG to set `watermarked=true` for all images that get processed. Then we would delete the ones with `watermarked=false` after the run. That's brilliant! I'll get working on that change, any objections to that approach @stacimc?

**Comment by stacimc** [comment]
No objections from me! Nice alternative to deleting everything and repopulating.

**Comment by krysal** [comment]
@AetherUnbound I was thinking more about checking whether the URLs contain spaces, and raising an exception if that happens. It's probably better to let each provider handle that, but the validation doesn't need to happen here! We can leave that improvement for a separate PR as well. I was just mentioning the idea that came to my mind 💡

**Comment by AetherUnbound** [comment]
Ahh, got it! Great idea! I've made an issue to encapsulate that 😄 https://github.com/WordPress/openverse-catalog/issues/1022

**Review by krysal — APPROVED** [review]
Sorry for the wait, this look great!

**Comment by AetherUnbound** [comment]
Confirmed that we have no watermarked images presently in the catalog:
```sql
deploy@localhost:openledger> select count(*) from image where provider='smk' and watermarked=true;
+-------+
| count |
|-------|
| 0     |
+-------+
SELECT 1
Time: 11.104s (11 seconds), executed in: 11.099s (11 seconds)
```

Going to merge this, then kick the SMK DAG off!

**Comment by AetherUnbound** [comment]
Oh dear, it seems like this had the opposite effect and instead _duplicated all of our results_ 😳 

```sql
deploy@localhost:openledger> select count(*) from image where provider='smk' and watermarked=true;
+-------+
| count |
|-------|
| 38527 |
+-------+
SELECT 1
Time: 0.228s
deploy@localhost:openledger> select count(*) from image where provider='smk' and watermarked=false;
+-------+
| count |
|-------|
| 69744 |
+-------+
SELECT 1
Time: 0.193s
deploy@localhost:openledger> select count(*) from image where provider='smk';
+--------+
| count  |
|--------|
| 108271 |
+--------+
SELECT 1
Time: 0.129s
```

I'm looking into this now, worst case we just drop the non-watermarked images which was the original plan anyway 😅

**Comment by AetherUnbound** [comment]
Sorry, I should have checked one other place, apparently we have 108k SMK results in the API database as well! So I guess that's expected, here's the current response from https://api.openverse.engineering/v1/images/stats/:

```json
    {
        "source_name": "smk",
        "display_name": "National Gallery of Denmark (SMK)",
        "source_url": "https://open.smk.dk/",
        "logo_url": null,
        "media_count": 108067
    }
```

So I suppose it worked as intended! We just have a lot more alternate images than primary ones 🙂 Proceeding with the delete.

**Comment by AetherUnbound** [comment]
Ran the following to prep the deletion:

```sql
deploy@localhost:openledger> create temporary table smk_deleted_2023_03_15 as select * from image where provider='smk';
SELECT 108271
Time: 0.428s
deploy@localhost:openledger> \copy smk_deleted_2023_03_15 to '/tmp/smk_deleted_2023_03_15.csv' DELIMITER ',' CSV HEADER;
Time: 5.323s (5 seconds), executed in: 5.323s (5 seconds)
```

Uploaded the latest data to s3://openverse-catalog/image/smk/smk_deleted_2023_03_15.csv

Ran this command to delete the non-watermarked images:
```sql
deploy@localhost:openledger> delete from image where provider='smk' and watermarked=false;
DELETE 69744
Time: 1.493s (1 second), executed in: 1.493s (1 second)
```

Then, to prevent misbehavior with the API, I set all the _remaining_ watermarks to `false`:

```sql
deploy@localhost:openledger> update image set watermarked=false where provider='smk';
UPDATE 38527
Time: 6.351s (6 seconds), executed in: 6.351s (6 seconds)
```

This is complete! I'll have a follow up PR to address #1020 shortly.

**Pull request merged**
