### PR TITLE
Use Airflow Variables for storing API keys

### LINKED ISSUE #209: Move API keys from .env to Airflow Variables
## Current Situation

Provider API keys look to be set in the [.env file](./openverse_catalog/env.template).

## Suggested Improvement

These keys could be moved into Airflow Variables instead.

## Benefit

* As we expand our list of providers, the current strategy would require that we also bloat the environment with each of the new API keys.
* Airflow encrypts and hides Variables when they contain secrets.
* API keys can be edited without having to restart the service.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes #209 by @AetherUnbound

## Description

This PR changes the provider API scripts to use [Airflow Variables](https://airflow.apache.org/docs/apache-airflow/stable/concepts/variables.html) rather than environment variables. The rationale/motivation for this can be found in-depth in #209, but the TL;DR is that this will make it easier for us to update the values in production without re-deploying the catalog.

As part of this effort, I've also unified the format for the keys. They now all begin with `AIRFLOW_VAR_` (in accordance with [Airflow's spec](https://airflow.apache.org/docs/apache-airflow/stable/howto/variable.html#storing-variables-in-environment-variables)) _as well as_ `API_KEY_<name>`. This consistency will make it easier to pick out the variables in the UI and within the environment since they will all have a common prefix.

**IMPORTANT**: If you have these variables defined locally, you will need to update your `.env` file!

## Testing Instructions

1. Run a provider DAG (e.g. Jamendo) normally, with the API key set correctly in the `.env` file. Observe that the script pulls data successfully.
1. Comment out the API key from the `.env` file. Observe that the DAG either fails or completes immediately with no data, since there is no API key available.
1. Add the API key manually in the UI (e.g. `API_KEY_JAMENDO`). Observe that an attempt to run the DAG succeeds even though the API key is not in the environment.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
Excellent! Will airflow still set the variables from the `.env` file, even if they can also be set via the UI? I tried to google and found this code which seems to indicate it will: https://github.com/apache/airflow/pull/7923

**Comment by AetherUnbound** [comment]
> Excellent! Will airflow still set the variables from the `.env` file, even if they can also be set via the UI?

It will! And actually Variables set using the environment have precedence (hence why we'll want to remove those from our deployment scripts). I talk about this a bit in the footnote of this comment here: https://github.com/WordPress/openverse-catalog/issues/209#issuecomment-951397140

**Comment by AetherUnbound** [comment]
Done in apache/airflow#21568

**Review by stacimc — APPROVED** [review]
Tested great for me! 🎉

**Pull request merged**
